name: Bookmarks Go

on:
  push:
    paths:
      - bookmarks-go/**
      - .github/workflows/bookmarks-go.yml
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './bookmarks-go'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: './bookmarks-go/go.mod'
        cache-dependency-path: "./bookmarks-go/go.sum"

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

    - name: Build Docker Image
      run: docker build -t sivaprasadreddy/bookmarks-go .
