name: Bookmarks SpringBoot

on:
  push:
    paths:
      - bookmarks-boot/**
      - .github/workflows/bookmarks-boot.yml
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './bookmarks-boot'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }} (${{ matrix.distribution }})
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify

      - name: Build Docker Image
        run: ./mvnw spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=bookmarks-boot
